name: obo2json 
on: 
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: download and setup path for github action binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v0.2.2/action_0.2.2_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: create a list of modified obo files 
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} pfc --payload-file ${GITHUB_EVENT_PATH} -o ${GITHUB_WORKSPACE}/commited.txt
      - name: Print list of files 
        if: ${{ success() }}
        run: for $f in `cat ${GITHUB_WORKSPACE}/commited.txt`;do echo $f;done
