name: Quality control check on obo files 
on: 
  pull_request

jobs:
  report:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: download and setup path for github action binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v2.0.0/action_2.0.0_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: create a list of modified obo files 
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} fc --payload-file ${GITHUB_EVENT_PATH} -o ${GITHUB_WORKSPACE}/committed.txt -e pull-request --ifs yaml
      - name: print list of files
        if: ${{ success() }}
        run: |
           if [ -e ${GITHUB_WORKSPACE}/committed.txt ]
           then
                cat ${GITHUB_WORKSPACE}/committed.txt
           else
                echo "no file exists"
           fi

