name: obo file reporter
on: 
  pull_request

jobs:
  report:
    env:
      REPORT_DIR: ${{ github.workspace }}/reports
      COMMIT_LIST_FILE: ${{ github.workspace }}/committed.txt
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: create report dir
        run: mkdir -p ${REPORT_DIR}
      - name: download and setup path for github action binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v2.0.0/action_2.0.0_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: create a list of modified obo files 
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} fc --payload-file ${GITHUB_EVENT_PATH} -o ${COMMIT_LIST_FILE} -e pull-request --ifs obo --sd true
      - name: run obo reporter
        uses: docker://dictybase/ontobot:master-f5c1055
        with:
          entrypoint: /usr/local/bin/report 
      - name: capture report for comment
        if: ${{ always() }}
        id: comment-body
        run: |
          if [ -e ${COMMIT_LIST_FILE} ]
          then
                body=$(cat ${REPORT_DIR}/*.tsv)
                body="${body//'%'/'%25'}"
                body="${body//$'\n'/'%0A'}"
                body="${body//$'\r'/'%0D'}"
                echo ::set-output name=body::$body
                echo ::set-output name=has_body::yes
          fi
      - name: Output failure report in pull request comment
        if: ${{ failure() && contains(steps.comment-body.outputs.has_body, 'yes') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
           issue-number: ${{ github.event.number }}
           body: ${{ steps.comment-body.outputs.body }}
           reactions: '-1'
      - name: Output success report in pull request comment
        if: ${{ success() && contains(steps.comment-body.outputs.has_body, 'yes') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
           issue-number: ${{ github.event.number }}
           body: |
             ## No errors in ontology report
           reactions: hooray, laugh

