name: Quality control check on obo files 
on: 
  pull_request

jobs:
  report:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: upload pull request payload
        uses: actions/upload-artifact@v2
        with:
          name: pull-request-create
          path: ${{ github.event_path }}
