name: Quality control check on obo files 
on: 
  pull_request

jobs:
  report:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: upload pull request payload
        uses: actions/upload-artifact@v2
        with:
          name: pull-request
          path: ${GITHUB_EVENT_PATH}/event.json
      - name: run report 
        uses: docker://dictybase/ontobot:1.7.7
        with:
          entrypoint: /usr/local/bin/report
      - name: list files
        if:  ${{ failure() }}
        run: ls -lht ${GITHUB_WORKSPACE}/reports

